#!/usr/bin/env python3
"""Build per-choice spec fields: subject, pose, clothes, color, art_style."""

from __future__ import annotations

# sleeve presets by RIASEC — hands-only framing
SLEEVES = {
    "R": "rolled work-shirt sleeves, sturdy cotton, cuff trim in accent",
    "I": "long lab-coat or knit sweater sleeves, neat cuffs",
    "A": "loose creative hoodie sleeves with light paint splatter",
    "S": "soft cardigan or volunteer vest sleeves, warm tones",
    "E": "smart casual blazer or polo sleeves, confident fit",
    "C": "pressed office shirt sleeves, crisp cuffs",
}

ACCESSORIES = {
    "R": "optional thin work gloves or tool belt edge visible",
    "I": "optional nitrile gloves or safety glasses on forehead edge (no face)",
    "A": "woven friendship bracelet or paint on fingers",
    "S": "simple wristband or volunteer lanyard at wrist only",
    "E": "watch or presentation clicker at wrist",
    "C": "pen clipped to shirt pocket at chest edge (no face)",
}


def choice_spec(
    *,
    code: str,
    primary: str,
    props: list[str],
    environment: str,
    left_hand: str,
    right_hand: str,
    gesture: str,
    camera_angle: str = "three-quarter top-down, centered",
    energy: str = "focused, approachable",
    sleeves: str | None = None,
    accessories: str | None = None,
    accent_use: list[str] | None = None,
    skin_tone: str = "warm neutral medium",
    background: str = "fully transparent — no floor cast, no scene box",
    shading: str = "minimal flat cel shadow under hands and main prop only",
    symbolic: bool = False,
) -> dict:
    accent_use = accent_use or [f"subtle {code} accent on main prop edges"]
    return {
        "subject": {
            "activity": primary,
            "primary_objects": props,
            "environment": environment,
            "symbolic": symbolic,
        },
        "pose": {
            "camera_angle": camera_angle,
            "left_hand": left_hand,
            "right_hand": right_hand,
            "gesture": gesture,
            "energy": energy,
            "framing": "hands and forearms only — crop above wrists, no faces",
        },
        "clothes": {
            "visible": "forearms and sleeves only",
            "sleeves": sleeves or SLEEVES[code],
            "accessories": accessories or ACCESSORIES[code],
        },
        "color": {
            "skin_tone": skin_tone,
            "background": background,
            "accent_placement": accent_use,
            "shading": shading,
        },
        "art_style": {
            "medium": "flat vector illustration",
            "line_weight_px": 2,
            "outline": "#2D2D2D",
            "fill": "solid flat fills, no gradients except soft 10% ambient on props",
            "mood": "friendly edu career app — Josie AI / STI Scope sticker family without frame",
            "not": ["photorealistic", "3D render", "SaaS dashboard", "text on image", "RIASEC letter", "border frame"],
        },
    }


# Per-slot overrides — 60 entries
CHOICE_SPECS: dict[str, dict] = {
    "1.1": choice_spec(
        code="R",
        primary="Building a robot kit",
        props=["unfinished cute robot body", "small screwdriver", "loose gears", "color-coded wires"],
        environment="light wooden workbench surface, cream paper under kit",
        left_hand="steadies robot chassis flat on bench",
        right_hand="inserts brass gear with precision grip",
        gesture="active assembly — mid-build moment",
        accent_use=["teal LED dots on robot chest", "teal cuff trim on work shirt"],
        accessories="thin grey work gloves, fingertips exposed",
    ),
    "1.2": choice_spec(
        code="I",
        primary="Analyzing stock market patterns",
        props=["tablet with candlestick chart", "stylus", "small trend-line overlay"],
        environment="minimal desk edge, soft lavender tint on tablet bezel only",
        left_hand="holds tablet at readable angle",
        right_hand="traces upward trend with stylus tip",
        gesture="analytical point-and-study",
        accent_use=["purple highlight on selected chart bars", "purple sweater cuff"],
        energy="curious, analytical",
    ),
    "2.1": choice_spec(
        code="A",
        primary="Creating digital artwork for a game",
        props=["graphics tablet", "stylus", "on-screen fantasy creature sketch", "color swatch chips"],
        environment="creative desk with scattered sticky notes (blank, no text)",
        left_hand="rests on tablet bezel",
        right_hand="draws flowing character line with stylus",
        gesture="creative stroke in progress",
        accent_use=["yellow UI accents on tablet UI chrome", "yellow paint fleck on sleeve"],
        sleeves="paint-splattered hoodie sleeves, yellow and lavender flecks",
    ),
    "2.2": choice_spec(
        code="S",
        primary="Tutoring classmates in math",
        props=["small whiteboard", "marker", "algebra equation (symbols only, no words)", "pencil"],
        environment="study table, warm soft light implied by flat highlight",
        left_hand="writes equation on board",
        right_hand="student hand holds pencil nearby — peer learning",
        gesture="teaching moment, collaborative",
        accent_use=["lavender marker cap", "lavender cardigan cuff"],
        energy="patient, encouraging",
    ),
    "3.1": choice_spec(
        code="E",
        primary="Starting an online business",
        props=["shipping box", "packing tape", "laptop with simple shop icon dashboard"],
        environment="home packing station, tidy",
        left_hand="folds box flap",
        right_hand="applies tape strip",
        gesture="entrepreneur shipping first order",
        accent_use=["coral shop icon on laptop", "coral polo cuff"],
        energy="energetic, optimistic",
    ),
    "3.2": choice_spec(
        code="C",
        primary="Organizing school records database",
        props=["monitor with sorted folder rows", "keyboard", "labeled color tabs (no text labels)"],
        environment="organized office nook",
        left_hand="on keyboard home row",
        right_hand="clicking mouse on sorted list",
        gesture="structured data entry",
        accent_use=["sky-blue selected row highlight", "sky-blue shirt cuff"],
        energy="calm, methodical",
    ),
    "4.1": choice_spec(
        code="R",
        primary="Repairing smartphone hardware",
        props=["open phone chassis", "precision screwdriver set", "anti-static mat"],
        environment="repair bench with tiny parts tray",
        left_hand="holds phone frame steady",
        right_hand="turns micro screwdriver on screw",
        gesture="precision repair",
        accent_use=["teal mat corner icon", "teal work glove fingertips"],
        accessories="ESD wrist strap at wrist, no face",
    ),
    "4.2": choice_spec(
        code="I",
        primary="Researching AI ethics",
        props=["research paper stack", "scales-of-justice icon", "neural-node diagram card"],
        environment="quiet study desk",
        left_hand="holds document edge",
        right_hand="points at diagram node",
        gesture="ethical analysis review",
        accent_use=["purple diagram nodes", "purple lab-coat cuff"],
        energy="thoughtful",
    ),
    "5.1": choice_spec(
        code="A",
        primary="Writing fantasy novel chapters",
        props=["laptop", "glowing dragon silhouette on screen", "coffee mug (steam curls only)"],
        environment="cozy writing nook implied by warm yellow highlight",
        left_hand="rests on laptop deck",
        right_hand="types on keyboard",
        gesture="imaginative writing flow",
        accent_use=["yellow dragon glow on screen", "yellow hoodie sleeve"],
        energy="inspired",
    ),
    "5.2": choice_spec(
        code="S",
        primary="Counseling peers through stress",
        props=["ceramic mug", "tissue box", "small plant on table"],
        environment="calm counseling table, soft lavender ambient",
        left_hand="offers mug forward",
        right_hand="open palm supportive gesture",
        gesture="gentle peer support",
        accent_use=["lavender mug stripe", "lavender soft cardigan"],
        energy="warm, calm",
    ),
    "6.1": choice_spec(
        code="E",
        primary="Marketing products on social media",
        props=["smartphone", "product photo on screen", "heart and share icons"],
        environment="bright creator desk",
        left_hand="holds phone upright for posting",
        right_hand="thumb hovering over post button",
        gesture="social campaign launch",
        accent_use=["coral heart icon", "coral blazer cuff"],
        energy="upbeat",
    ),
    "6.2": choice_spec(
        code="C",
        primary="Processing financial transactions",
        props=["calculator", "receipt stack", "spreadsheet on monitor"],
        environment="accounting desk, neat stacks",
        left_hand="keys numbers on calculator",
        right_hand="sorts receipt pile by date tabs",
        gesture="systematic finance processing",
        accent_use=["sky-blue calculator keys", "sky-blue pressed shirt"],
        energy="steady",
    ),
    "7.1": choice_spec(
        code="R",
        primary="Installing home security systems",
        props=["wall bracket", "compact security camera", "screwdriver", "pencil level"],
        environment="interior wall section cross-section",
        left_hand="holds camera to bracket",
        right_hand="drives mounting screw",
        gesture="hardware install",
        accent_use=["teal status LED on camera", "teal work shirt"],
        accessories="tool belt corner visible at frame edge",
    ),
    "7.2": choice_spec(
        code="I",
        primary="Developing climate prediction models",
        props=["laptop", "world map heat overlay", "line graph prediction curves"],
        environment="research desk",
        left_hand="on trackpad scrolling map",
        right_hand="points at graph peak",
        gesture="climate data interpretation",
        accent_use=["purple graph line", "purple knit sleeves"],
        energy="focused research",
    ),
    "8.1": choice_spec(
        code="A",
        primary="Designing streetwear fashion",
        props=["sketchbook", "hoodie flat sketch", "fabric swatches", "markers"],
        environment="fashion studio table",
        left_hand="pins swatch to page",
        right_hand="sketches bold hoodie outline",
        gesture="streetwear design",
        accent_use=["yellow highlight on sketch", "yellow paint on fingers"],
        sleeves="oversized streetwear hoodie sleeves, paint marks",
    ),
    "8.2": choice_spec(
        code="S",
        primary="Coaching youth sports teams",
        props=["coach whistle on lanyard", "clipboard with diagram Xs and Os", "cone at field edge"],
        environment="sports field sideline, green flat strip only",
        left_hand="holds clipboard",
        right_hand="raises whistle ready to signal",
        gesture="sideline coaching",
        accent_use=["lavender team bib edge on clipboard", "lavender vest sleeve"],
        energy="motivating",
    ),
    "9.1": choice_spec(
        code="E",
        primary="Pitching startup ideas to investors",
        props=["small easel board", "lightbulb icon", "growth arrow chart", "clicker"],
        environment="pitch room table edge",
        left_hand="open presenting gesture toward board",
        right_hand="holds clicker",
        gesture="confident pitch",
        accent_use=["coral growth arrow", "coral blazer cuff"],
        energy="bold, persuasive",
    ),
    "9.2": choice_spec(
        code="C",
        primary="Managing supply chain logistics",
        props=["conveyor belt diagram", "labeled boxes A/B/C icons only", "routing arrows"],
        environment="operations planning desk",
        left_hand="slides box icon along route",
        right_hand="marks checkpoint on flowchart",
        gesture="logistics coordination",
        accent_use=["sky-blue route arrows", "sky-blue office shirt"],
        energy="organized",
    ),
    "10.1": choice_spec(
        code="R",
        primary="Building sustainable furniture",
        props=["wooden chair leg", "sandpaper block", "wood shavings", "clamps"],
        environment="woodshop bench",
        left_hand="clamps leg steady",
        right_hand="sands along grain",
        gesture="craft woodworking",
        accent_use=["teal clamp handle", "teal rolled work sleeves"],
        accessories="sawdust on gloves, no face",
    ),
    "10.2": choice_spec(
        code="I",
        primary="Studying marine biology specimens",
        props=["magnifying glass", "shells in shallow tray", "specimen forceps", "field journal"],
        environment="lab tray on neutral surface",
        left_hand="holds shell with forceps",
        right_hand="magnifies surface pattern",
        gesture="specimen examination",
        accent_use=["purple journal bookmark ribbon", "purple lab sleeves"],
        energy="meticulous",
    ),
    "11.1": choice_spec(
        code="A",
        primary="Producing music tracks",
        props=["MIDI keyboard", "laptop with waveform display", "headphones around neck edge only"],
        environment="bedroom studio desk",
        left_hand="plays chord on keys",
        right_hand="adjusts laptop slider",
        gesture="music production",
        accent_use=["yellow waveform peaks", "yellow hoodie with headphone cable"],
        energy="creative flow",
    ),
    "11.2": choice_spec(
        code="S",
        primary="Volunteering at community health camp",
        props=["first-aid kit", "volunteer armband (no text)", "folded blanket stack"],
        environment="community table setup",
        left_hand="passes kit across table",
        right_hand="receives from partner hands — teamwork",
        gesture="volunteer handoff",
        accent_use=["lavender cross icon on kit", "lavender volunteer vest"],
        energy="helpful",
    ),
    "12.1": choice_spec(
        code="E",
        primary="Leading corporate negotiations",
        props=["contract document", "pen", "conference table edge"],
        environment="boardroom table, minimal",
        left_hand="firm handshake grip",
        right_hand="matching handshake — deal closing",
        gesture="professional handshake over contracts",
        accent_use=["coral tie edge at bottom frame", "coral blazer sleeves"],
        energy="confident",
    ),
    "12.2": choice_spec(
        code="C",
        primary="Auditing company accounts",
        props=["ledger book", "green checkmark stickers", "audit spreadsheet printout"],
        environment="audit desk with neat piles",
        left_hand="turns ledger page",
        right_hand="places checkmark on line item",
        gesture="verification audit",
        accent_use=["sky-blue column headers on sheet", "sky-blue shirt cuffs"],
        energy="precise",
    ),
    "13.1": choice_spec(
        code="R",
        primary="Maintaining drone equipment",
        props=["quadcopter drone", "hex wrench", "propeller blade", "maintenance stand"],
        environment="tech bench",
        left_hand="holds drone body on stand",
        right_hand="tightens prop nut with wrench",
        gesture="drone repair",
        accent_use=["teal propeller tips", "teal mechanic gloves"],
    ),
    "13.2": choice_spec(
        code="I",
        primary="Researching quantum computing",
        props=["monitor with qubit lattice diagram", "notebook with equations (symbols only)"],
        environment="advanced physics desk",
        left_hand="scribes equation symbol",
        right_hand="points at qubit node on screen",
        gesture="theoretical research",
        accent_use=["purple lattice nodes", "purple lab-coat sleeves"],
        energy="deep focus",
    ),
    "14.1": choice_spec(
        code="S",
        primary="Teaching coding to kids",
        props=["laptop with block-code colors", "child-size hands smaller scale", "star sticker reward"],
        environment="classroom table",
        left_hand="adult hand guides child hand on trackpad",
        right_hand="child hand clicks colorful code block",
        gesture="mentored learning",
        accent_use=["lavender code blocks", "lavender teacher cardigan"],
        energy="patient, fun",
    ),
    "14.2": choice_spec(
        code="A",
        primary="Designing museum exhibits",
        props=["display pedestal", "mini diorama model", "label stand (blank plaque)"],
        environment="museum prep table",
        left_hand="positions model figure on pedestal",
        right_hand="adjusts spotlight angle tool",
        gesture="exhibit curation",
        accent_use=["yellow spotlight cone", "yellow creative sleeves"],
        energy="curatorial",
    ),
    "15.1": choice_spec(
        code="E",
        primary="Managing e-commerce store",
        props=["laptop dashboard", "cart icon", "order notification badge", "shipping label roll"],
        environment="seller workstation",
        left_hand="scrolls order list",
        right_hand="clicks fulfill button",
        gesture="store management",
        accent_use=["coral cart icon", "coral smart polo"],
        energy="busy, proactive",
    ),
    "15.2": choice_spec(
        code="C",
        primary="Optimizing database efficiency",
        props=["server rack icon on monitor", "performance graph trending up", "keyboard"],
        environment="server admin desk",
        left_hand="types query shortcut",
        right_hand="points at optimized graph green zone",
        gesture="DB tuning",
        accent_use=["sky-blue graph line", "sky-blue office sleeves"],
        energy="technical, calm",
    ),
    "16.1": choice_spec(
        code="R",
        primary="Installing solar farm panels",
        props=["two solar panels", "MC4 cable connector", "work harness strap at edge"],
        environment="outdoor install frame, sunny yellow highlight only",
        left_hand="aligns panel edge",
        right_hand="clicks cable connector",
        gesture="renewable install",
        accent_use=["teal connector housing", "teal hi-vis sleeve stripe"],
        accessories="work gloves, harness clip at wrist",
    ),
    "16.2": choice_spec(
        code="I",
        primary="Documenting wildlife behavior",
        props=["binoculars", "field notebook", "bird silhouettes in far background"],
        environment="field observation, soft horizon line only",
        left_hand="focuses binocular dial",
        right_hand="writes observation sketch of bird",
        gesture="field research",
        accent_use=["purple notebook cover", "purple field jacket cuff"],
        energy="quiet observation",
    ),
    "17.1": choice_spec(
        code="S",
        primary="Helping refugees settle locally",
        props=["welcome basket with bread and fruit", "house key on ribbon", "small potted plant"],
        environment="doorstep welcome scene — symbolic, hopeful",
        left_hand="offers basket handle forward",
        right_hand="extends key on open palm",
        gesture="welcoming gesture",
        accent_use=["lavender ribbon on key", "lavender cardigan"],
        symbolic=True,
        energy="hopeful, gentle",
    ),
    "17.2": choice_spec(
        code="A",
        primary="Creating public space murals",
        props=["paint roller", "mural wall section with bold geometric shapes", "paint tray"],
        environment="outdoor wall panel",
        left_hand="guides roller upward",
        right_hand="holds tray steady",
        gesture="mural painting",
        accent_use=["yellow sun motif on wall", "yellow paint on roller"],
        sleeves="paint-covered street-art sleeves",
    ),
    "18.1": choice_spec(
        code="E",
        primary="Planning corporate takeover",
        props=["chess board", "tall king piece", "strategy chart cards"],
        environment="strategy war-room table",
        left_hand="moves chess piece forward",
        right_hand="slides chart card into place",
        gesture="strategic planning",
        accent_use=["coral chess piece highlight", "coral blazer"],
        energy="calculating, bold",
    ),
    "18.2": choice_spec(
        code="C",
        primary="Standardizing filing systems",
        props=["color-coded folders", "label maker", "filing cabinet drawer"],
        environment="records room",
        left_hand="pulls folder from drawer",
        right_hand="applies color label tab",
        gesture="filing standardization",
        accent_use=["sky-blue folder tabs", "sky-blue shirt"],
        energy="methodical",
    ),
    "19.1": choice_spec(
        code="R",
        primary="Fixing electric bicycles",
        props=["e-bike battery pack", "multimeter probes", "hex key set"],
        environment="bike repair stand edge",
        left_hand="holds battery housing open",
        right_hand="tests lead with probe",
        gesture="e-mobility repair",
        accent_use=["teal battery indicator LEDs", "teal mechanic sleeves"],
    ),
    "19.2": choice_spec(
        code="I",
        primary="Studying virus mutations",
        props=["microscope eyepiece edge", "petri dish", "abstract soft cell blobs"],
        environment="lab bench — symbolic, non-graphic",
        left_hand="adjusts microscope focus knob",
        right_hand="positions petri dish gently",
        gesture="microbiology study",
        accent_use=["purple cell blob accents", "purple lab gloves"],
        symbolic=True,
        energy="scientific, calm",
    ),
    "20.1": choice_spec(
        code="S",
        primary="Mentoring first-generation students",
        props=["textbook", "graduation cap charm keychain", "bookmark"],
        environment="library table",
        left_hand="slides textbook toward mentee side",
        right_hand="offers cap charm as encouragement",
        gesture="mentorship gift",
        accent_use=["lavender bookmark", "lavender mentor cardigan"],
        energy="supportive",
    ),
    "20.2": choice_spec(
        code="A",
        primary="Illustrating science textbooks",
        props=["drawing tablet", "cell diagram with organelles", "reference photo of leaf"],
        environment="illustration desk",
        left_hand="holds reference leaf",
        right_hand="stylizes organelle on tablet",
        gesture="scientific illustration",
        accent_use=["yellow nucleus highlight", "yellow paint-fleck sleeves"],
    ),
    "21.1": choice_spec(
        code="I",
        primary="Analyzing consumer behavior trends",
        props=["tablet", "bar chart", "pie chart", "trend arrow"],
        environment="market research desk",
        left_hand="steadies tablet",
        right_hand="swipes to next chart panel",
        gesture="consumer analytics",
        accent_use=["purple trend arrow", "purple sweater cuff"],
        energy="analytical",
    ),
    "21.2": choice_spec(
        code="C",
        primary="Creating tax compliance reports",
        props=["document stack", "approved stamp", "tax form grid (numbers only)"],
        environment="compliance office desk",
        left_hand="aligns report stack",
        right_hand="stamps approval mark",
        gesture="regulatory filing",
        accent_use=["sky-blue form header band", "sky-blue shirt"],
        energy="precise",
    ),
    "22.1": choice_spec(
        code="E",
        primary="Directing non-profit organization",
        props=["round table edge", "heart-in-hands logo sketch", "mission sticky notes blank"],
        environment="nonprofit meeting space",
        left_hand="gestures open toward team (second hand pair edge only)",
        right_hand="points at heart logo sketch",
        gesture="mission leadership",
        accent_use=["coral heart logo", "coral blazer"],
        energy="inspiring",
    ),
    "22.2": choice_spec(
        code="C",
        primary="Quality-checking manufacturing outputs",
        props=["clipboard", "product unit on belt", "checklist ticks"],
        environment="factory QC station simplified",
        left_hand="holds product for inspection",
        right_hand="marks checklist tick",
        gesture="quality assurance",
        accent_use=["sky-blue checklist header", "sky-blue uniform sleeves"],
    ),
    "23.1": choice_spec(
        code="R",
        primary="Assembling telescope components",
        props=["telescope tube", "lens element", "precision calipers"],
        environment="optics assembly bench",
        left_hand="holds lens in calipers",
        right_hand="fits lens into tube mount",
        gesture="precision optics assembly",
        accent_use=["teal lens coating reflection", "teal lab work sleeves"],
        energy="careful",
    ),
    "23.2": choice_spec(
        code="I",
        primary="Developing cancer treatment trials",
        props=["lab flask with soft glow", "microscope", "hope ribbon icon subtle"],
        environment="research lab — uplifting symbolic",
        left_hand="holds flask to light",
        right_hand="adjusts microscope slide gently",
        gesture="medical research hope",
        accent_use=["purple flask liquid accent", "purple lab coat"],
        symbolic=True,
        energy="hopeful, serious but not sad",
    ),
    "24.1": choice_spec(
        code="S",
        primary="Counseling at-risk youth",
        props=["park bench edge", "open palm gesture", "small notebook closed"],
        environment="quiet park — symbolic safe space",
        left_hand="open relaxed palm offered",
        right_hand="second person hand reaching to accept support — no faces",
        gesture="supportive listening pose",
        accent_use=["lavender bench slat accent", "lavender soft sleeves"],
        symbolic=True,
        energy="calm, safe",
    ),
    "24.2": choice_spec(
        code="A",
        primary="Designing inclusive playgrounds",
        props=["site plan", "wheelchair-accessible swing model", "ramp icon", "color pencils"],
        environment="architect desk",
        left_hand="places swing model on plan",
        right_hand="draws ramp curve on plan",
        gesture="inclusive design planning",
        accent_use=["yellow swing seat accent", "yellow designer sleeves"],
    ),
    "25.1": choice_spec(
        code="I",
        primary="Testing water purification systems",
        props=["clear water sample vial", "test strip kit", "pH color chart"],
        environment="environmental lab bench",
        left_hand="holds vial to light",
        right_hand="dips test strip",
        gesture="water quality test",
        accent_use=["purple chart band", "purple field jacket sleeves"],
    ),
    "25.2": choice_spec(
        code="C",
        primary="Managing payroll systems",
        props=["keyboard", "payslip stack", "calendar with pay-day dot icons"],
        environment="HR admin desk",
        left_hand="types employee code",
        right_hand="sorts payslip envelopes",
        gesture="payroll processing",
        accent_use=["sky-blue calendar dots", "sky-blue office shirt"],
    ),
    "26.1": choice_spec(
        code="R",
        primary="Building disaster-resistant housing",
        props=["house model", "reinforced steel beam", "blueprint roll"],
        environment="construction planning table",
        left_hand="sets beam on model roof",
        right_hand="unrolls blueprint corner",
        gesture="resilient construction",
        accent_use=["teal beam accent stripe", "teal work vest sleeves"],
    ),
    "26.2": choice_spec(
        code="C",
        primary="Planning city recycling programs",
        props=["three sort bins with icons", "recycling arrows", "route map"],
        environment="municipal planning desk",
        left_hand="drops paper icon in bin",
        right_hand="draws collection route arrow",
        gesture="recycling program design",
        accent_use=["sky-blue arrow paths", "sky-blue municipal shirt"],
    ),
    "27.1": choice_spec(
        code="S",
        primary="Art therapy for trauma survivors",
        props=["canvas", "paintbrush", "grey strokes turning into color blooms"],
        environment="art therapy easel — symbolic healing",
        left_hand="holds canvas edge",
        right_hand="brush pulls color through grey",
        gesture="healing through art",
        accent_use=["lavender to yellow color bloom", "lavender soft sleeves"],
        symbolic=True,
        energy="gentle, restorative",
    ),
    "27.2": choice_spec(
        code="A",
        primary="Brand identity design for startups",
        props=["logo sketches on paper", "color swatch fan", "tablet with logo preview"],
        environment="branding studio desk",
        left_hand="fans swatch cards",
        right_hand="sketches logo mark with pen",
        gesture="brand identity craft",
        accent_use=["yellow primary swatch", "yellow creative sleeves"],
        energy="inventive",
    ),
    "28.1": choice_spec(
        code="E",
        primary="Launching tech incubator program",
        props=["laptop", "rocket icon lifting", "seedling sprouts in pots"],
        environment="startup incubator desk",
        left_hand="types launch command",
        right_hand="waters seedling while rocket anim on screen",
        gesture="ecosystem launch",
        accent_use=["coral rocket trail", "coral startup polo"],
        energy="visionary",
    ),
    "28.2": choice_spec(
        code="I",
        primary="Developing cybersecurity protocols",
        props=["laptop", "shield lock icon", "network node diagram"],
        environment="security ops desk",
        left_hand="on keyboard shortcut keys",
        right_hand="points at shield icon on screen",
        gesture="security hardening",
        accent_use=["purple shield glow", "purple tech hoodie"],
        energy="alert, focused",
    ),
    "29.1": choice_spec(
        code="R",
        primary="Search-and-rescue operations",
        props=["handheld radio", "first-aid kit", "trail marker post"],
        environment="mountain trail sign — no danger imagery",
        left_hand="keys radio mic",
        right_hand="lifts kit strap ready",
        gesture="rescue readiness",
        accent_use=["teal radio display", "teal rescue vest sleeves"],
        accessories="reflective stripe on vest cuff",
    ),
    "29.2": choice_spec(
        code="S",
        primary="Organizing community gardens",
        props=["seedling trays", "hand trowel", "raised garden bed soil"],
        environment="community garden plot",
        left_hand="plants seedling in soil",
        right_hand="holds trowel aside",
        gesture="community planting",
        accent_use=["lavender garden glove back", "lavender volunteer tee sleeve"],
        energy="communal, warm",
    ),
    "30.1": choice_spec(
        code="E",
        primary="Negotiating international trade deals",
        props=["globe desk ornament", "trade document folders", "handshake icon card"],
        environment="international business table",
        left_hand="extends handshake",
        right_hand="partner handshake — deal close",
        gesture="global trade agreement",
        accent_use=["coral globe meridian line", "coral suit cuff"],
        energy="diplomatic confidence",
    ),
    "30.2": choice_spec(
        code="C",
        primary="Creating corporate compliance manuals",
        props=["thick binder", "checkmark compliance seal", "tab dividers"],
        environment="compliance library desk",
        left_hand="opens binder rings",
        right_hand="presses seal sticker on cover",
        gesture="compliance documentation",
        accent_use=["sky-blue tab dividers", "sky-blue office shirt"],
        energy="thorough",
    ),
}
